//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adresar.KontaktService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KontaktService.IKontaktService")]
    public interface IKontaktService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontaktService/DohvatiAktivneKontakte", ReplyAction="http://tempuri.org/IKontaktService/DohvatiAktivneKontakteResponse")]
        Adresar.WcfService.Models.Kontakt[] DohvatiAktivneKontakte();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontaktService/DohvatiAktivneKontakte", ReplyAction="http://tempuri.org/IKontaktService/DohvatiAktivneKontakteResponse")]
        System.Threading.Tasks.Task<Adresar.WcfService.Models.Kontakt[]> DohvatiAktivneKontakteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKontaktServiceChannel : Adresar.KontaktService.IKontaktService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KontaktServiceClient : System.ServiceModel.ClientBase<Adresar.KontaktService.IKontaktService>, Adresar.KontaktService.IKontaktService {
        
        public KontaktServiceClient() {
        }
        
        public KontaktServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KontaktServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KontaktServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KontaktServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Adresar.WcfService.Models.Kontakt[] DohvatiAktivneKontakte() {
            return base.Channel.DohvatiAktivneKontakte();
        }
        
        public System.Threading.Tasks.Task<Adresar.WcfService.Models.Kontakt[]> DohvatiAktivneKontakteAsync() {
            return base.Channel.DohvatiAktivneKontakteAsync();
        }
    }
}
